### PR TITLE
[HMA-3889] - Migrate to new bintray and upgrade some other dependencies that did n…

### PR DESCRIPTION
**Pull request by georgeherby**
…ot have any need for code changes!

### CODE REVIEW

**Review by mrolfe88 — APPROVED** [review]

**Comment by robcharlwood** [comment]
test this please jenkins! :)

**Comment by robcharlwood** [comment]
test this jenkins

**Comment by robcharlwood** [comment]
test this please jenkins!

**Comment by robcharlwood** [comment]
test this please jenkins

**Comment by robcharlwood** [comment]
test this please jenkins

**Comment by robcharlwood** [comment]
test this please jenkins

**Comment by robcharlwood** [comment]
test this please jenkins

**Comment by robcharlwood** [comment]
test this please jenkins!

**Comment by robcharlwood** [comment]
test this please jenkins!

**Comment by robcharlwood** [comment]
test this please jenkins

**Pull request merged**
